apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - name: webhook
        image: steveww/webhook:latest
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          timeoutSeconds: 3
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          timeoutSeconds: 3
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
            
