apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: catch-all
  namespace: wego-system
spec:
  providerRef:
    name: generic-webhook
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
